language: emacs-lisp

services:
  - docker

sudo: required

env:
  matrix:
    - emacs=emacs-snapshot

before_install:
  - docker pull ubuntu:rolling
  - sudo mv ../.emacs.d ~
  - lsb_release -a
  - emacs -version

script:
  ./test_startup.sh
